pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'your-credentials-id', url: 'https://github.com/your-username/messaging_app.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest --junitxml=messaging_app/report.xml'
            }
        }
        stage('Generate Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }
    }
}
